// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2n8JxMVdJpjulhnB3Eu4IPIUYFwUCunQ',
    appId: '1:307330618373:web:139cabeff3dc400d77b86c',
    messagingSenderId: '307330618373',
    projectId: 'taskapp-6a5c3',
    authDomain: 'taskapp-6a5c3.firebaseapp.com',
    storageBucket: 'taskapp-6a5c3.appspot.com',
    measurementId: 'G-5SFYH5P2S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcahiNDNqwb-tDFVUxLnD9PU_2SEU0Pe8',
    appId: '1:307330618373:android:893e0bd2d7d4b54577b86c',
    messagingSenderId: '307330618373',
    projectId: 'taskapp-6a5c3',
    storageBucket: 'taskapp-6a5c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4-uffMcRxdFeC2oAmIZuG-A-bNaTlmwM',
    appId: '1:307330618373:ios:a4b37a2fe655f18e77b86c',
    messagingSenderId: '307330618373',
    projectId: 'taskapp-6a5c3',
    storageBucket: 'taskapp-6a5c3.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4-uffMcRxdFeC2oAmIZuG-A-bNaTlmwM',
    appId: '1:307330618373:ios:e24e754127d6ea0577b86c',
    messagingSenderId: '307330618373',
    projectId: 'taskapp-6a5c3',
    storageBucket: 'taskapp-6a5c3.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
